apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-games-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  RabbitMQ__Host: "rabbitmq.fcg.svc.cluster.local"
  RabbitMQ__User: "guest"
  RabbitMQ__Exchange: "fcg.events"
  Elasticsearch__Url: "http://elasticsearch.fcg.svc.cluster.local:9200"
  Elasticsearch__Index: "fcg-games"
  Jwt__Issuer: "fcg"
  Jwt__Audience: "fcg"
  OpenTelemetry__OtlpEndpoint: "http://jaeger.fcg.svc.cluster.local:4317"
  # URL interna do payments (comunicação síncrona de fallback)
  PaymentsService__BaseUrl: "http://fcg-payments-service.fcg.svc.cluster.local:8080"
